x-config-common: &config-common
  networks:
    billy_project:
  env_file:
    - ./.env
  environment: &env-common
    POSTGRES_APP_DB: ${POSTGRES_APP_DB:-billy_project}


services:
  billy_project:
    container_name: billy_project_app
    <<: *config-common
    environment:
      <<: *env-common
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-billy_project.settings.development}
      GUNICORN_WORKERS: 1
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./:/home/billy/billy_project

  postgres:
    image: "postgres:15.4-alpine3.18"
    <<: *config-common
    container_name: billy_project_postgres
    environment:
      <<: *env-common
      POSTGRES_USER: ${POSTGRES_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-admin}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./900-create_db.sh:/docker-entrypoint-initdb.d/900-create_db.sh

networks:
  billy_project:
    driver: bridge

volumes:
  postgres-data:
