# Generated by Django 5.0.6 on 2024-06-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Billy', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='books.book')),
                ('successes', models.ManyToManyField(blank=True, related_name='adventures', to='books.success')),
            ],
        ),
        migrations.CreateModel(
            name='AdventureChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='billy.adventure')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_chapters', to='books.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='adventure',
            name='visited_chapters',
            field=models.ManyToManyField(blank=True, related_name='adventures', through='billy.AdventureChapter', to='books.chapter'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='billy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adventure', to='billy.billy'),
        ),
        migrations.CreateModel(
            name='BillyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(related_name='available_classes', to='books.book')),
            ],
            options={
                'verbose_name_plural': 'Billy classes',
            },
        ),
        migrations.AddField(
            model_name='billy',
            name='billy_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billys', to='billy.billyclass'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('WEAPON', 'Arme'), ('EQUIPMENT', 'Équipement'), ('TOOLS', 'Outils'), ('OTHER', 'Autre')], max_length=100)),
                ('books', models.ManyToManyField(related_name='available_items', to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='billy',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='billys', to='billy.item'),
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('books', models.ManyToManyField(related_name='available_stats', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_effects', to='billy.item')),
                ('stat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billy.stat')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='effects',
            field=models.ManyToManyField(related_name='affected_stats', through='billy.ItemEffect', to='billy.stat'),
        ),
        migrations.CreateModel(
            name='BillyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('billy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billy.billy')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billy.stat')),
            ],
        ),
        migrations.AddField(
            model_name='billy',
            name='stats',
            field=models.ManyToManyField(through='billy.BillyStat', to='billy.stat'),
        ),
    ]
