# Generated by Django 5.0.6 on 2024-06-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[('FDCN', 'La Forteresse du Chaudron Noir'), ('CDSI', "La Corne des Sables d'Ivoire"), ('LLDV', 'La Lance de Valkar')], default='FDCN', max_length=500),
        ),
    ]
