# Generated by Django 5.0.6 on 2024-06-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='success',
            name='book',
        ),
    ]
